name        : xorg-server
version     : 1.18.4
release     : 48
source      :
    - https://www.x.org/releases/individual/xserver/xorg-server-1.18.4.tar.gz : 4ba0e6c2c96650f1d1606572196143054005eb88d31c33b15a81d50886f26713
license     :
    - MIT
summary     : The Xorg Server is the core of the X Window system.
component   : xorg.server
description : |
    The Xorg Server is the core of the X Window system.
rundeps     :
    - dbus-launch
    - linux-driver-management
replaces    :
    - glamor-egl
    - xorg-driver-video-modesetting
builddeps   :
    - pkgconfig(bigreqsproto)
    - pkgconfig(compositeproto)
    - pkgconfig(dmxproto)
    - pkgconfig(dri2proto)
    - pkgconfig(dri3proto)
    - pkgconfig(epoxy)
    - pkgconfig(fontsproto)
    - pkgconfig(fontutil)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glproto)
    - pkgconfig(inputproto)
    - pkgconfig(libunwind)
    - pkgconfig(nettle)
    - pkgconfig(pciaccess)
    - pkgconfig(pixman-1)
    - pkgconfig(presentproto)
    - pkgconfig(randrproto)
    - pkgconfig(recordproto)
    - pkgconfig(renderproto)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(videoproto)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - pkgconfig(xcb-aux)
    - pkgconfig(xcb-ewmh)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-randr)
    - pkgconfig(xcb-render)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(xcb-shape)
    - pkgconfig(xcb-shm)
    - pkgconfig(xcb-xkb)
    - pkgconfig(xcmiscproto)
    - pkgconfig(xdmcp)
    - pkgconfig(xf86dgaproto)
    - pkgconfig(xf86driproto)
    - pkgconfig(xf86vidmodeproto)
    - pkgconfig(xfont)
    - pkgconfig(xfont2)
    - pkgconfig(xi)
    - pkgconfig(xineramaproto)
    - pkgconfig(xkbfile)
    - pkgconfig(xmuu)
    - pkgconfig(xorg-macros)
    - pkgconfig(xrender)
    - pkgconfig(xshmfence)
    - pkgconfig(xtrans)
optimize   :
    - no-bind-now
    - no-symbolic
setup      : |
    %apply_patches
    %reconfigure --with-xkb-output=/var/lib/xkb \
                 --enable-install-setuid \
                 --enable-suid-wrapper \
                 --disable-systemd-logind \
                 --with-int10=x86emu \
                 --with-xkb-path=/usr/share/X11/xkb \
                 --with-fontrootdir=/usr/share/fonts \
                 --enable-glamor \
                 --enable-xwayland \
                 --enable-kdrive \
                 --enable-kdrive-kbd \
                 --enable-kdrive-evdev \
                 --enable-kdrive-mouse \
                 --enable-xephyr \
                 --enable-dri \
                 --enable-dri2 \
                 --enable-dri3 \
                 --enable-xcsecurity \
                 --enable-config-udev \
                 --enable-config-udev-kms \
                 --disable-selective-werror \
                 --disable-static
build      : |
    %make
install    : |
    %make_install

    # tmpfiles
    rm -rf $installdir/var
    install -D -m 00644 $pkgfiles/xorg-server.tmpfiles $installdir/%libdir%/tmpfiles.d/xorg-server.conf

    # ldm
    install -m 00755 -D -d $installdir/%libdir%/glx-provider/default
    mv $installdir/%libdir%/xorg/modules/extensions/libglx.so $installdir/%libdir%/glx-provider/default/.
    ln -sv libglx.so $installdir/%libdir%/glx-provider/default/libglx.so.1
