name       : xorg-server
version    : 1.20.10
release    : 70
source     :
    - https://www.x.org/releases/individual/xserver/xorg-server-1.20.10.tar.gz : 02f2198608b6191b7f8c65158bd4613734ec1c5c3d6784c5177f41b5cd2d30a3
license    : MIT
component  : xorg.server
summary    : The Xorg Server is the core of the X Window system
description: |
    The Xorg Server is the core of the X Window system.
optimize   :
    - no-bind-now
    - no-symbolic
patterns   :
    - xvfb :
        - /usr/bin/Xvfb
        - /usr/bin/xvfb-run
        - /usr/share/man/man1/Xvfb.1
rundeps    :
    - dbus-launch
    - linux-driver-management
    - xvfb :
        - xauth
        - xkbcomp
        - xkeyboard-config
replaces   :
    - glamor-egl
    - xorg-driver-video-modesetting
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(epoxy)
    - pkgconfig(fontutil)
    - pkgconfig(freetype2)
    - pkgconfig(libgcrypt)
    - pkgconfig(libtirpc)
    - pkgconfig(libunwind)
    - pkgconfig(nettle)
    - pkgconfig(pciaccess)
    - pkgconfig(pixman-1)
    - pkgconfig(tslib)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-eglstream-protocols)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xaw7)
    - pkgconfig(xcb-aux)
    - pkgconfig(xcb-ewmh)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(xdmcp)
    - pkgconfig(xfont2)
    - pkgconfig(xi)
    - pkgconfig(xkbcomp)
    - pkgconfig(xkbfile)
    - pkgconfig(xmu)
    - pkgconfig(xorg-macros)
    - pkgconfig(xpm)
    - pkgconfig(xproto)
    - pkgconfig(xrender)
    - pkgconfig(xshmfence)
    - pkgconfig(xtrans)
setup      : |
    %apply_patches
    %meson_configure \
      -Ddefault_font_path=/usr/share/fonts \
      -Ddri1=true \
      -Ddri2=true \
      -Ddri3=true \
      -Dglamor=true \
      -Dint10=x86emu \
      -Dipv6=true \
      -Dlibunwind=true \
      -Dsuid_wrapper=true \
      -Dsystemd_logind=true \
      -Dudev=true \
      -Dudev_kms=true \
      -Dxcsecurity=true \
      -Dxorg=true \
      -Dxephyr=true \
      -Dxkb_dir=/usr/share/X11/xkb \
      -Dxkb_output_dir=/var/lib/xkb \
      -Dxwayland=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    ln -s /usr/bin/Xorg $installdir/usr/bin/X

    # Provide xvfb-run to complement Xvfb
    install -Dm00755 $pkgfiles/xvfb-run $installdir/usr/bin/xvfb-run

    # tmpfiles
    rm -rf $installdir/var
    install -Dm00644 $pkgfiles/xorg-server.tmpfiles $installdir/%libdir%/tmpfiles.d/xorg-server.conf
