name       : xorg-server
version    : 1.19.6
release    : 53
source     :
    - https://www.x.org/releases/individual/xserver/xorg-server-1.19.6.tar.gz : 3c0e4a354a6b1d5d357b121357946ee8ffdb2f52158b2e63e105be9cef013168
license    : MIT
component  : xorg.server
summary    : The Xorg Server is the core of the X Window system.
description: |
    The Xorg Server is the core of the X Window system.
patterns   :
    - xvfb :
        - /usr/bin/Xvfb
        - /usr/bin/xvfb-run
        - /usr/share/man/man1/Xvfb.1
rundeps    :
    - dbus-launch
    - linux-driver-management
    - xvfb :
        - xauth
        - xkbcomp
        - xkeyboard-config
replaces   :
    - glamor-egl
    - xorg-driver-video-modesetting
builddeps  :
    - pkgconfig(bigreqsproto)
    - pkgconfig(compositeproto)
    - pkgconfig(dmxproto)
    - pkgconfig(dri2proto)
    - pkgconfig(dri3proto)
    - pkgconfig(epoxy)
    - pkgconfig(fontsproto)
    - pkgconfig(fontutil)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glproto)
    - pkgconfig(inputproto)
    - pkgconfig(libunwind)
    - pkgconfig(nettle)
    - pkgconfig(pciaccess)
    - pkgconfig(pixman-1)
    - pkgconfig(presentproto)
    - pkgconfig(randrproto)
    - pkgconfig(recordproto)
    - pkgconfig(renderproto)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(tslib)
    - pkgconfig(videoproto)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xau)
    - pkgconfig(xaw7)
    - pkgconfig(x11)
    - pkgconfig(xcb-aux)
    - pkgconfig(xcb-ewmh)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-randr)
    - pkgconfig(xcb-render)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(xcb-shape)
    - pkgconfig(xcb-shm)
    - pkgconfig(xcb-xkb)
    - pkgconfig(xcmiscproto)
    - pkgconfig(xdmcp)
    - pkgconfig(xf86dgaproto)
    - pkgconfig(xf86driproto)
    - pkgconfig(xf86vidmodeproto)
    - pkgconfig(xfont)
    - pkgconfig(xfont2)
    - pkgconfig(xi)
    - pkgconfig(xineramaproto)
    - pkgconfig(xkbfile)
    - pkgconfig(xmu)
    - pkgconfig(xmuu)
    - pkgconfig(xorg-macros)
    - pkgconfig(xpm)
    - pkgconfig(xrender)
    - pkgconfig(xshmfence)
    - pkgconfig(xt)
    - pkgconfig(xtrans)
optimize   :
    - no-bind-now
    - no-symbolic
setup      : |
    %apply_patches
    %reconfigure --with-xkb-output=/var/lib/xkb \
                 --enable-install-setuid \
                 --enable-suid-wrapper \
                 --with-int10=x86emu \
                 --with-xkb-path=/usr/share/X11/xkb \
                 --with-fontrootdir=/usr/share/fonts \
                 --enable-glamor \
                 --enable-xwayland \
                 --enable-kdrive \
                 --enable-kdrive-kbd \
                 --enable-kdrive-evdev \
                 --enable-kdrive-mouse \
                 --enable-xephyr \
                 --enable-dri \
                 --enable-dri2 \
                 --enable-dri3 \
                 --enable-xcsecurity \
                 --enable-config-udev \
                 --enable-config-udev-kms \
                 --disable-selective-werror \
                 --disable-static
build      : |
    %make
install    : |
    %make_install

    # Provide xvfb-run to complement Xvfb
    install -Dm00755 $pkgfiles/xvfb-run $installdir/usr/bin/xvfb-run

    # tmpfiles
    rm -rf $installdir/var
    install -D -m 00644 $pkgfiles/xorg-server.tmpfiles $installdir/%libdir%/tmpfiles.d/xorg-server.conf
