name       : xorg-server
version    : 1.20.11
release    : 72
source     :
    - https://www.x.org/releases/individual/xserver/xorg-server-1.20.11.tar.gz : 4e9341c96f5ed0f6b9491ed732c501303479d3fe21da280c768a1822d7e5d352
license    : MIT
component  : xorg.server
summary    : The Xorg Server is the core of the X Window system
description: |
    The Xorg Server is the core of the X Window system.
optimize   :
    - no-bind-now
    - no-symbolic
patterns   :
    - xvfb :
        - /usr/bin/Xvfb
        - /usr/bin/xvfb-run
        - /usr/share/man/man1/Xvfb.1
rundeps    :
    - dbus-launch
    - linux-driver-management
    - xvfb :
        - xauth
        - xkbcomp
        - xkeyboard-config
replaces   :
    - glamor-egl
    - xorg-driver-video-modesetting
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(epoxy)
    - pkgconfig(fontutil)
    - pkgconfig(freetype2)
    - pkgconfig(libgcrypt)
    - pkgconfig(libunwind)
    - pkgconfig(nettle)
    - pkgconfig(pciaccess)
    - pkgconfig(pixman-1)
    - pkgconfig(tslib)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-eglstream-protocols)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xaw7)
    - pkgconfig(xcb-aux)
    - pkgconfig(xcb-ewmh)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(xdmcp)
    - pkgconfig(xfont2)
    - pkgconfig(xi)
    - pkgconfig(xkbfile)
    - pkgconfig(xmu)
    - pkgconfig(xorg-macros)
    - pkgconfig(xpm)
    - pkgconfig(xproto)
    - pkgconfig(xrender)
    - pkgconfig(xshmfence)
    - pkgconfig(xtrans)
setup      : |
    %apply_patches
    %reconfigure --with-xkb-output=/var/lib/xkb \
                 --enable-install-setuid \
                 --enable-suid-wrapper \
                 --with-int10=x86emu \
                 --with-xkb-path=/usr/share/X11/xkb \
                 --with-fontrootdir=/usr/share/fonts \
                 --enable-glamor \
                 --enable-xwayland \
                 --enable-kdrive \
                 --enable-kdrive-kbd \
                 --enable-kdrive-evdev \
                 --enable-kdrive-mouse \
                 --enable-xephyr \
                 --enable-dri \
                 --enable-dri2 \
                 --enable-dri3 \
                 --enable-xcsecurity \
                 --enable-config-udev \
                 --enable-config-udev-kms \
                 --disable-selective-werror \
                 --disable-static
build      : |
    %make
install    : |
    %make_install

    # Provide xvfb-run to complement Xvfb
    install -Dm00755 $pkgfiles/xvfb-run $installdir/usr/bin/xvfb-run

    # tmpfiles
    rm -rf $installdir/var
    install -Dm00644 $pkgfiles/xorg-server.tmpfiles $installdir/%libdir%/tmpfiles.d/xorg-server.conf
